-- Seed data for FCH database
-- Run this after schema.sql
-- Sourced from "Informações para o Site Institucional - Faculdade de Ciências Humanas" (UCAN)

-- Insert Decana
INSERT INTO decana (nome, titulo, mensagem) VALUES
  ('Dra. Ana Bela Pereira Loureiro',
   'Decana da Faculdade de Ciências Humanas',
   'É com imenso orgulho que dou as boas-vindas a todos os visitantes do nosso site institucional. A Faculdade de Ciências Humanas (FCH) da Universidade Católica de Angola tem como missão formar homens e mulheres plenos de valores humanos, éticos e cristãos, dotados de conhecimentos científicos, técnicos e profissionais inovadores, capazes de servir a sociedade com competência, responsabilidade, rectidão moral, espírito crítico e compromisso com o bem comum.

Ao longo da nossa trajectória, iniciada em 2003, a Faculdade tem desempenhado um papel relevante na formação de profissionais qualificados nas áreas da Psicologia e das Línguas e Administração, contribuindo para o desenvolvimento académico, científico, social e cultural de Angola.

Investimos continuamente na qualificação do nosso corpo docente, na investigação científica através do Centro Interdisciplinar de Ensino e Investigação (CIEI), na extensão universitária por via do Laboratório de Psicologia, e na criação de novos programas de pós-graduação e especialização.

Convido-vos a conhecer melhor a nossa Faculdade, os nossos cursos e as nossas actividades de investigação e extensão. Juntos, podemos continuar a construir um futuro mais justo, inclusivo e sustentável para Angola.');

-- Insert Professores (first, as cursos reference them)
INSERT INTO professores (nome, slug, titulo, departamento, email, telefone, biografia, areas_investigacao, gabinete, foto_url) VALUES
  ('Dra. Ana Bela Pereira Loureiro',
   'ana-bela-loureiro',
   'Linguista',
   'Decanato',
   'anabela.loureiro@ucan.edu',
   NULL,
   'Decana da Faculdade de Ciências Humanas da Universidade Católica de Angola. Linguista, com actuação nos Estudos Linguísticos e na Investigação.',
   ARRAY['Estudos Linguísticos', 'Investigação'],
   NULL,
   '/images/decana/decana.jpg'),

  ('Dra. Evanilse dos Santos Diogo',
   'evanilse-diogo',
   'Psicóloga Clínica',
   'Psicologia Clínica',
   'evanilse.diogo@ucan.edu',
   NULL,
   'Vice-Decana para a Graduação da FCH. Psicóloga Clínica, docente da Pós-Graduação Profissional em Consulta Psicológica (Psicoterapia Cognitivo-Comportamental) e supervisora de estágio em Psicologia Clínica. Foi Coordenadora do Laboratório de Psicologia entre 2022 e 2023.',
   ARRAY['Psicoterapia Cognitivo-Comportamental', 'Investigação'],
   NULL,
   '/images/professores/Evanilse.PNG'),

  ('Mestre Manuel Armando Dala',
   'manuel-dala',
   'Psicólogo do Trabalho e das Organizações',
   'Psicologia do Trabalho e das Organizações',
   'manuel.dala@ucan.edu',
   '+244 923 949 052',
   'Vice-Decano para as Pós-Graduações, Investigação e Extensão e Chefe do Departamento de Psicologia do Trabalho e das Organizações da FCH. Coordena a Especialização em Gestão do Ensino Superior (EGES) e a Pós-Graduação Profissional em Capacitação Pedagógica (PGPCP), e lecciona Saúde Mental, Qualidade de Vida e Psicodinâmica do Trabalho na Pós-Graduação em Gestão de Pessoas 360º.',
   ARRAY['Investigação', 'Consultoria Organizacional'],
   NULL,
   '/images/professores/mdala.jpg'),

  ('Doutora Helena Veloso',
   'helena-veloso',
   'Psicóloga Clínica',
   'Psicologia Clínica',
   'helena.veloso@ucan.edu',
   '+244 928 524 737',
   'Chefe do Departamento de Psicologia Clínica, Directora do Centro Interdisciplinar de Ensino e Investigação (CIEI) e Coordenadora da Pós-Graduação Profissional em Consulta Psicológica. Foi Coordenadora do Laboratório de Psicologia entre 2020 e 2022 e supervisiona o Plantão Psicológico. Lecciona Terapia Psicanalítica: Teoria e Prática.',
   ARRAY['Psicologia Clínica', 'Psicanálise', 'Saúde Mental'],
   NULL,
   NULL),

  ('Doutor Domingos Carlos Pascoal',
   'domingos-pascoal',
   'Doutor',
   'Línguas Românicas e Literaturas Modernas',
   'domingos.pascoal@ucan.edu',
   NULL,
   'Chefe do Departamento de Línguas Românicas e Literaturas Modernas, coordenando a formação linguística e cultural em Língua Portuguesa, Francesa, Latim, Italiano e outras áreas da Linguística.',
   ARRAY['Linguística', 'Literatura', 'Tradução'],
   NULL,
   NULL),

  ('Doutor Francisco Matete',
   'francisco-matete',
   'Doutor',
   'Línguas Germânicas e Literaturas Modernas',
   'francisco.matete@ucan.edu',
   NULL,
   'Chefe do Departamento de Línguas Germânicas e Literaturas Modernas, responsável pela formação linguística em Língua Inglesa e estudos interculturais.',
   ARRAY['Língua Inglesa', 'Tradução e Interpretação', 'Linguística Aplicada'],
   NULL,
   '/images/professores/Matete.jpg'),

  ('Professor Doutor João Manuel Saveia Daniel Francisco',
   'joao-saveia',
   'Doutor em Psicologia',
   'Psicologia do Trabalho e das Organizações',
   NULL,
   NULL,
   'Doutor em Psicologia pela Universidade Federal da Bahia (UFBA); Mestre em Administração (Organização e Recursos Humanos) e Especialista em Gestão Estratégica de Negócios e em Gestão Estratégica de Recursos Humanos, todos pela UFMG; Licenciado em Psicologia. Lecciona Recursos Humanos no Coração do Ensino Superior (EGES) e Psicologia Organizacional e do Trabalho (Gestão de Pessoas 360º), e é supervisor de estágio em Psicologia Organizacional e do Trabalho.',
   ARRAY['Psicologia Organizacional', 'Gestão de Recursos Humanos'],
   NULL,
   '/images/professores/Jsaveia.jpg'),

  ('Professor Doutor Tuca Manuel',
   'tuca-manuel',
   'Doutor em Ciências da Educação',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Doutor em Ciências da Educação (Organização e Gestão Escolar) e Especialista em Organizações Educativas e Administração Educacional, ambos pela Universidade do Minho, Portugal. Lecciona Fundamentos do Ensino Superior na Especialização em Gestão do Ensino Superior.',
   ARRAY['Organização e Gestão Escolar', 'Administração Educacional'],
   NULL,
   NULL),

  ('Professor Doutor Ken Kalala Ndalamba',
   'ken-ndalamba',
   'Doutor em Gestão e Administração Pública',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Doutor em Gestão e Administração Pública e Mestre em Liderança e Gestão pela University of the Western Cape, África do Sul; Pós-graduado em Ensino Superior (Docência e Gestão) pela University of South Africa. Lecciona Planeamento Estratégico na Especialização em Gestão do Ensino Superior.',
   ARRAY['Liderança e Gestão', 'Administração Pública'],
   NULL,
   NULL),

  ('Doutor Manuel Zau',
   'manuel-zau',
   'Doutor',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Processos de Criação, Avaliação e Acreditação de Cursos na Especialização em Gestão do Ensino Superior.',
   ARRAY['Avaliação e Acreditação de Cursos'],
   NULL,
   NULL),

  ('Professor Doutor Eurico Wongo Gungula',
   'eurico-gungula',
   'Doutor em Ciências Pedagógicas',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Doutor em Ciências Pedagógicas (Dinâmica de Formação Interpretativa em Matemática Superior) pelo Centro de Estudos Educacionais e Centro de Estudos de Educação Superior "Manuel F. Gran" da Universidade de Oriente, Cuba; Mestre em Novas Tecnologias Aplicadas à Educação (Matemática) pela Universidade Máximo Gómez Báez, Cuba. Lecciona Investigação na Especialização em Gestão do Ensino Superior.',
   ARRAY['Ciências Pedagógicas', 'Novas Tecnologias na Educação'],
   NULL,
   NULL),

  ('Professor Doutor Nlando Matondo Faustino',
   'nlando-faustino',
   'Doutor em Filosofia',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Doutoramento em Filosofia (Filosofia Política) e Diploma de Estudos Avançados em Filosofia Política pela Universidade de Évora, Portugal; Mestrado em Ciências da Educação (Administração e Gestão Educacional) pela Universidade de Évora; Mestrado em Filosofia pela Universidade Gregoriana (extensão RDC); Bacharelato em Filosofia pelo Seminário Maior de São Paulo, Uíge, Angola. Lecciona Extensão (EGES) e A Universidade e as Novas Tendências Pedagógicas (PGPCP).',
   ARRAY['Filosofia Política', 'Administração e Gestão Educacional'],
   NULL,
   '/images/professores/Nlando.jpg'),

  ('Professora Doutora Ana Maria Alfaiate Rocha',
   'ana-rocha',
   'Doutora em Psicologia da Educação',
   'Colaboradora - Pós-Graduações',
   NULL,
   NULL,
   'Doutora em Psicologia da Educação e Especialista em Avaliação e Intervenção Psicológica em Contextos Educativos, ambos pela Faculdade de Psicologia da Universidade de Lisboa, Portugal. Lecciona Gestão e Liderança de Equipas na Especialização em Gestão do Ensino Superior e é supervisora de estágio em Psicologia Organizacional e do Trabalho.',
   ARRAY['Psicologia da Educação', 'Avaliação Psicológica'],
   NULL,
   '/images/professores/AnaRocha.jpeg'),

  ('Professor Doutor Samuel Helena Tumbula',
   'samuel-tumbula',
   'Doutor em Ciências da Educação',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Doutor e Mestre em Ciências da Educação (Administração e Organização Escolar) pela Universidade Católica Portuguesa; MBA em Gerenciamento de Projectos pela Fundação Getúlio Vargas, Brasil; Pós-graduado em Direito do Trabalho e Segurança Social pela Universidade Católica Portuguesa; formação em Metodologia Qualitativa e Quantitativa pela Universidade de Coimbra. Lecciona Redacção de Projectos de Investigação Científica (EGES) e Metodologia de Investigação Científica (Consulta Psicológica).',
   ARRAY['Administração e Organização Escolar', 'Metodologia de Investigação'],
   NULL,
   '/images/professores/SamuelTumbula.jpeg'),

  ('Professor Doutor Albertino Candimba Sebastião',
   'albertino-candimba',
   'Doutor em Educação',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Doutoramento e Mestrado em Educação (Gestão Estratégica e Avaliação Institucional em IES); MBA em Gestão Educacional; Especialização em Ensino da Física e Química pela Universidade de Aveiro. Lecciona Gestão Académica na Especialização em Gestão do Ensino Superior.',
   ARRAY['Gestão Estratégica e Avaliação Institucional'],
   NULL,
   NULL),

  ('Professor Mestre Pedro Manuel Marques Fernandes',
   'pedro-fernandes',
   'Mestre em Gestão de Empresas',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'MBA em Gestão de Empresas e Licenciatura em Gestão de Empresas, Lisboa; Curso de Formação de Formadores; Cursos de Especialização em Contabilidade. Lecciona Gestão Financeira (EGES) e Prática Pedagógica I e II e Planificação do Processo de Ensino-Aprendizagem (PGPCP).',
   ARRAY['Gestão Financeira', 'Formação Pedagógica'],
   NULL,
   NULL),

  ('José Gomes',
   'jose-gomes',
   'Docente',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Didáctica do Ensino Superior na Pós-Graduação Profissional em Capacitação Pedagógica.',
   ARRAY['Didáctica do Ensino Superior'],
   NULL,
   NULL),

  ('Professor Doutor José Chivinda',
   'jose-chivinda',
   'Doutor em Ciências da Educação',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Doutoramento em Ciências da Educação pela Universidade Católica Portuguesa. Foi Director Geral do Instituto Superior Dom Bosco (2013-2019), vinculado à UCAN. Lecciona Comunicação Educativa e Métodos e Meios de Ensino na Pós-Graduação Profissional em Capacitação Pedagógica.',
   ARRAY['Ciências da Educação', 'Metodologias de Ensino'],
   NULL,
   NULL),

  ('Professor Doutor João Francisco',
   'joao-francisco',
   'Doutor em Direito',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Doutor em Direito pela Universitat de València, Espanha, com investigação pós-doutoral como Visiting Fellow na University of Oslo e no Centro de Direitos Humanos da Universidade de Pretória; Mestre em Direito pela Universitat de València. Professor de Direito Internacional na Faculdade de Direito da UCAN e Advogado, Membro da Ordem dos Advogados de Angola. Lecciona Questões Normativas do Ensino Superior na PGPCP.',
   ARRAY['Direito Internacional', 'Direitos Humanos'],
   NULL,
   NULL),

  ('Nelson Quissungo',
   'nelson-quissungo',
   'Docente',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Questões Éticas no Ensino Superior na Pós-Graduação Profissional em Capacitação Pedagógica.',
   ARRAY['Ética no Ensino Superior'],
   NULL,
   NULL),

  ('Professora Mestre Maria Helena Miguel',
   'maria-helena-miguel',
   'Mestre em Ensino da Língua Portuguesa',
   'Colaboradora - Pós-Graduações',
   NULL,
   NULL,
   'Mestre em Ensino da Língua Portuguesa e Licenciada em Língua Portuguesa pelo ISCED/Luanda, com formação complementar na Universidade do Minho, Portugal. Lecciona Processo de Avaliação das Aprendizagens na Pós-Graduação Profissional em Capacitação Pedagógica.',
   ARRAY['Ensino da Língua Portuguesa', 'Avaliação das Aprendizagens'],
   NULL,
   NULL),

  ('Abel Cassule',
   'abel-cassule',
   'Docente',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Técnicas de Elaboração de Projectos de Investigação e Extensão na Pós-Graduação Profissional em Capacitação Pedagógica.',
   ARRAY['Projectos de Investigação e Extensão'],
   NULL,
   NULL),

  ('Adriana Silva',
   'adriana-silva',
   'Docente',
   'Colaboradora - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Tecnologias da Informação e Comunicação no Ensino na Pós-Graduação Profissional em Capacitação Pedagógica.',
   ARRAY['Tecnologias da Informação e Comunicação'],
   NULL,
   NULL),

  ('Lorena Henriquez',
   'lorena-henriquez',
   'Coordenadora',
   'Colaboradora - Pós-Graduações',
   'lorena.henriquez@ucan.edu',
   '+244 928 524 737',
   'Coordenadora da Pós-Graduação Profissional em Gestão de Pessoas 360º, onde lecciona Fundamentos Estratégicos da Gestão de Pessoas e do Capital Humano e o Projecto Integrador em Gestão de Pessoas 360º.',
   ARRAY['Gestão de Pessoas', 'Capital Humano'],
   NULL,
   NULL),

  ('Zacarias Samba dos Santos',
   'zacarias-samba',
   'Docente',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Desenvolvimento Humano, Liderança e Gestão de Competências Organizacionais na Pós-Graduação Profissional em Gestão de Pessoas 360º.',
   ARRAY['Liderança', 'Gestão de Competências Organizacionais'],
   NULL,
   NULL),

  ('Márcia Nigiolela',
   'marcia-nigiolela',
   'Docente',
   'Colaboradora - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Direito do Trabalho Aplicado à Gestão de Pessoas e às Relações Laborais na Pós-Graduação Profissional em Gestão de Pessoas 360º.',
   ARRAY['Direito do Trabalho'],
   NULL,
   NULL),

  ('Edvaldo Calitamba',
   'edvaldo-calitamba',
   'Docente',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Direito do Trabalho Aplicado à Gestão de Pessoas e às Relações Laborais na Pós-Graduação Profissional em Gestão de Pessoas 360º.',
   ARRAY['Direito do Trabalho'],
   NULL,
   NULL),

  ('Drª Jeanine Silveira',
   'jeanine-silveira',
   'Docente',
   'Colaboradora - Pós-Graduações',
   'jeanine.silveira@ucan.edu',
   NULL,
   'Docente da disciplina Comunicação Estratégica, Cultura Organizacional e Gestão de Conflitos na Pós-Graduação Profissional em Gestão de Pessoas 360º.',
   ARRAY['Comunicação Estratégica', 'Gestão de Conflitos'],
   NULL,
   '/images/professores/Jeanine.jpg'),

  ('Celsio Cosme',
   'celsio-cosme',
   'Docente',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Inteligência Artificial Aplicada à Gestão de Pessoas na Pós-Graduação Profissional em Gestão de Pessoas 360º.',
   ARRAY['Inteligência Artificial Aplicada à Gestão de Pessoas'],
   NULL,
   NULL),

  ('José Sebastião',
   'jose-sebastiao',
   'Docente',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Ética e Deontologia Profissional na Pós-Graduação Profissional em Consulta Psicológica.',
   ARRAY['Ética e Deontologia Profissional'],
   NULL,
   NULL),

  ('Anibal Simões',
   'anibal-simoes',
   'Docente',
   'Colaborador - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Elaboração de Artigo Científico na Pós-Graduação Profissional em Consulta Psicológica.',
   ARRAY['Elaboração de Artigos Científicos'],
   NULL,
   NULL),

  ('Cátia Pargano',
   'catia-pargano',
   'Docente',
   'Colaboradora - Pós-Graduações',
   NULL,
   NULL,
   'Docente da disciplina Psicoterapias Humanistas e Existenciais: Teoria e Clínica na Pós-Graduação Profissional em Consulta Psicológica.',
   ARRAY['Psicoterapias Humanistas e Existenciais'],
   NULL,
   NULL),

  ('Licenciada Arieth Francisco Andrade',
   'arieth-andrade',
   'Licenciada',
   'Coordenação de Estágios',
   'arieth.andrade@ucan.edu',
   '+244 928 001 050',
   'Coordenadora de Estágios da Faculdade de Ciências Humanas, assegurando a articulação entre a Faculdade e as instituições parceiras que acolhem os estudantes durante os estágios curriculares.',
   ARRAY['Gestão de Estágios'],
   NULL,
   NULL),

  ('Manassés Apolinário',
   'manasses-apolinario',
   'Psicólogo Clínico',
   'Laboratório de Psicologia',
   'manasses.apolinario@ucan.edu',
   '+244 923 820 314',
   'Coordenador do Laboratório de Psicologia (LaP_FCH_UCAN) e Coordenador dos Cursos de Formação Complementar da FCH.',
   ARRAY['Psicologia Clínica'],
   NULL,
   NULL),

  ('Lisvalda Morais',
   'lisvalda-morais',
   'Psicóloga do Trabalho e das Organizações',
   'Laboratório de Psicologia',
   NULL,
   NULL,
   'Coordenadora Adjunta do Laboratório de Psicologia (LaP_FCH_UCAN).',
   ARRAY['Psicologia do Trabalho e das Organizações'],
   NULL,
   NULL),

  ('Dra. Mangani Lopes',
   'mangani-lopes',
   'Psicóloga Clínica',
   'Psicologia Clínica',
   NULL,
   NULL,
   'Supervisora de estágio em Psicologia Clínica. Coautora, com a Doutora Helena Veloso, do artigo "Atitudes das famílias face aos membros portadores de Psicose" (2024).',
   ARRAY['Psicologia Clínica', 'Saúde Mental e Família'],
   NULL,
   '/images/professores/Mangani.png'),

  ('Dr. Artur Luciano',
   'artur-luciano',
   'Docente',
   'Psicologia Clínica',
   NULL,
   NULL,
   'Supervisor de estágio em Psicologia Clínica.',
   ARRAY['Psicologia Clínica'],
   NULL,
   '/images/professores/ArturLuciano.png'),

  ('Dra. Vânia Filipe',
   'vania-filipe',
   'Docente',
   'Psicologia Clínica',
   NULL,
   NULL,
   'Vice-Decana Interina para a Graduação. Licenciada pela FCH, colabora com o Laboratório de Psicologia e é supervisora de estágio em Psicologia Clínica.',
   ARRAY['Psicologia Clínica'],
   NULL,
   NULL);

-- Insert Cursos with all fields
INSERT INTO cursos (nome, slug, descricao, duracao, grau, tipo, objetivos, perfil_graduado, saidas_profissionais, coordenador_id, pdf_url) VALUES
  ('Licenciatura em Psicologia - Opção Clínica',
   'psicologia-clinica',
   'O curso de Psicologia, opção Clínica, foi criado pelo Decreto Executivo n.º 496/15 e é ministrado pela FCH desde 2007. Forma profissionais capacitados para compreender, avaliar e intervir em processos de saúde mental.',
   '5 anos',
   'Licenciatura',
   'graduacao',
   ARRAY['Desenvolver competências de avaliação psicológica, diagnóstico e intervenção clínica', 'Promover a investigação científica em Psicologia aplicada ao contexto angolano', 'Formar profissionais capazes de actuar em hospitais, escolas, instituições públicas e ONGs', 'Fomentar a promoção da saúde mental na comunidade'],
   'O licenciado actua na promoção da saúde mental em dispositivos e organizações de Psicologia Clínica, na saúde comunitária, na docência, na investigação e na consultoria a partir do saber psicológico.',
   ARRAY['Avaliação Psicológica', 'Psicoterapia', 'Saúde Mental', 'Investigação'],
   (SELECT id FROM professores WHERE slug = 'helena-veloso'),
   NULL),

  ('Licenciatura em Psicologia - Opção do Trabalho e das Organizações',
   'psicologia-trabalho-organizacoes',
   'O curso de Psicologia, opção do Trabalho e das Organizações, foi criado pelo Decreto Executivo n.º 496/15 e é ministrado pela FCH desde 2007. Forma profissionais capazes de intervir em contextos organizacionais, empresariais e institucionais.',
   '5 anos',
   'Licenciatura',
   'graduacao',
   ARRAY['Desenvolver competências de consultoria organizacional e gestão de recursos humanos', 'Promover a investigação científica em Psicologia do Trabalho e das Organizações', 'Formar profissionais capazes de actuar em empresas, organizações públicas e ONGs', 'Fortalecer a ligação com o mercado de trabalho através de estágios'],
   'O licenciado actua no recrutamento e selecção, na formação e desenvolvimento, na consultoria organizacional, na gestão de recursos humanos, na análise de clima e cultura organizacional, na investigação, no ensino e no empreendedorismo.',
   ARRAY['Recrutamento e Seleção', 'Consultoria Organizacional', 'Gestão de RH', 'Investigação'],
   (SELECT id FROM professores WHERE slug = 'manuel-dala'),
   NULL),

  ('Licenciatura em Línguas e Administração',
   'linguas-administracao',
   'O curso de Línguas e Administração integra competências linguísticas, culturais e organizacionais, preparando profissionais para actuar em contextos nacionais e internacionais.',
   '4 anos',
   'Licenciatura',
   'graduacao',
   ARRAY['Desenvolver competências em línguas estrangeiras e tradução', 'Promover a comunicação intercultural', 'Formar profissionais em administração e gestão', 'Preparar para os desafios do mercado de trabalho contemporâneo'],
   'O licenciado dispõe de um leque vasto de saídas profissionais, incluindo administração, tradução, organizações internacionais, jornalismo, diplomacia e gestão de empresas.',
   ARRAY['Tradução', 'Administração', 'Diplomacia', 'Comunicação Social'],
   (SELECT id FROM professores WHERE slug = 'domingos-pascoal'),
   NULL),

  ('Especialização em Gestão do Ensino Superior',
   'especializacao-gestao-ensino-superior',
   'Curso criado e homologado pelo Decreto Executivo n.º 108/22, no âmbito do Programa de Apoio ao Ensino Superior (UNI.AO), que visa fortalecer as capacidades de liderança de quadros das Instituições de Ensino Superior angolanas.',
   '600 horas (+ módulos opcionais)',
   'Pós-Graduação',
   'pos-graduacao',
   ARRAY['Fortalecer as capacidades de liderança de quadros das Instituições de Ensino Superior', 'Desenvolver competências em gestão do ensino, investigação e extensão'],
   'O formando desenvolve competências de liderança e gestão académica aplicáveis a instituições de ensino superior públicas, público-privadas e privadas.',
   ARRAY['Gestão do Ensino Superior', 'Liderança Académica', 'Investigação', 'Extensão'],
   (SELECT id FROM professores WHERE slug = 'manuel-dala'),
   NULL),

  ('Pós-Graduação Profissional em Capacitação Pedagógica',
   'capacitacao-pedagogica',
   'Programa (PGPCP) criado e homologado pelo Decreto Executivo n.º 60/19, que desenvolve as capacidades didáctico-pedagógicas dos docentes do ensino superior.',
   '405 horas',
   'Pós-Graduação',
   'pos-graduacao',
   ARRAY['Desenvolver as capacidades didáctico-pedagógicas dos docentes do ensino superior', 'Habilitar para a docência universitária'],
   'O formando adquire competências profissionais para a docência universitária, requisito para o acesso e continuação na carreira docente nas Instituições de Ensino Superior.',
   ARRAY['Didáctica do Ensino Superior', 'Pedagogia Universitária', 'Avaliação de Aprendizagens'],
   (SELECT id FROM professores WHERE slug = 'manuel-dala'),
   NULL),

  ('Pós-Graduação Profissional em Gestão de Pessoas 360º',
   'gestao-pessoas-360',
   'Programa que integra Gestão de Pessoas, Psicologia Organizacional, Direito do Trabalho e Inteligência Artificial Aplicada à Gestão de Pessoas (Decreto Executivo n.º 450/22).',
   '240 horas',
   'Pós-Graduação',
   'pos-graduacao',
   ARRAY['Desenvolver competências avançadas em Gestão de Pessoas, Psicologia Organizacional, Direito do Trabalho e IA aplicada ao capital humano'],
   'O formando desenvolve competências avançadas para profissionais que actuam nas áreas de Recursos Humanos, Relações Laborais e Desenvolvimento Organizacional.',
   ARRAY['Gestão de Pessoas', 'Psicologia Organizacional', 'Direito do Trabalho', 'Inteligência Artificial'],
   (SELECT id FROM professores WHERE slug = 'lorena-henriquez'),
   NULL),

  ('Pós-Graduação Profissional em Consulta Psicológica',
   'consulta-psicologica',
   'Programa que desenvolve competências avançadas para psicólogos e profissionais de saúde mental, integrando as vertentes Cognitivo-Comportamental e Psicanalítica.',
   'Fins de semana',
   'Pós-Graduação',
   'pos-graduacao',
   ARRAY['Fortalecer a capacidade de avaliação, intervenção e acompanhamento psicológico', 'Promover uma abordagem científica, ética e centrada na pessoa'],
   'O formando aprimora a sua prática clínica em avaliação, intervenção e acompanhamento psicológico em diferentes contextos e populações.',
   ARRAY['Terapia Psicanalítica', 'Psicoterapia Cognitivo-Comportamental', 'Ética Profissional'],
   (SELECT id FROM professores WHERE slug = 'helena-veloso'),
   NULL);

-- Insert Formação (para docentes com percurso académico detalhado no documento institucional)
INSERT INTO formacao (professor_id, grau, instituicao, ano) VALUES
  ((SELECT id FROM professores WHERE slug = 'joao-saveia'), 'Doutoramento em Psicologia', 'Universidade Federal da Bahia (UFBA)', NULL),
  ((SELECT id FROM professores WHERE slug = 'joao-saveia'), 'Mestrado em Administração (Organização e Recursos Humanos)', 'UFMG', NULL),
  ((SELECT id FROM professores WHERE slug = 'joao-saveia'), 'Especialização em Gestão Estratégica de Negócios', 'UFMG', NULL),
  ((SELECT id FROM professores WHERE slug = 'joao-saveia'), 'Especialização em Gestão Estratégica de Recursos Humanos', 'UFMG', NULL),
  ((SELECT id FROM professores WHERE slug = 'joao-saveia'), 'Licenciatura em Psicologia', NULL, NULL),

  ((SELECT id FROM professores WHERE slug = 'tuca-manuel'), 'Doutoramento em Ciências da Educação (Organização e Gestão Escolar)', 'Universidade do Minho, Portugal', NULL),
  ((SELECT id FROM professores WHERE slug = 'tuca-manuel'), 'Especialização em Organizações Educativas e Administração Educacional', 'Universidade do Minho, Portugal', NULL),

  ((SELECT id FROM professores WHERE slug = 'ken-ndalamba'), 'Doutoramento em Gestão e Administração Pública', 'University of the Western Cape, África do Sul', NULL),
  ((SELECT id FROM professores WHERE slug = 'ken-ndalamba'), 'Mestrado (MA) em Liderança e Gestão', 'University of the Western Cape, África do Sul', NULL),
  ((SELECT id FROM professores WHERE slug = 'ken-ndalamba'), 'Pós-Graduação em Ensino Superior (PGCE:SF&FET)', 'University of South Africa', NULL),

  ((SELECT id FROM professores WHERE slug = 'eurico-gungula'), 'Doutoramento em Ciências Pedagógicas', 'Universidade Máximo Gómez Báez / Universidade de Oriente, Cuba', NULL),
  ((SELECT id FROM professores WHERE slug = 'eurico-gungula'), 'Mestrado em Novas Tecnologias Aplicadas à Educação (Matemática)', 'Universidade Máximo Gómez Báez, Cuba', NULL),

  ((SELECT id FROM professores WHERE slug = 'nlando-faustino'), 'Doutoramento em Filosofia (Filosofia Política)', 'Universidade de Évora, Portugal', '2022'),
  ((SELECT id FROM professores WHERE slug = 'nlando-faustino'), 'Diploma de Estudos Avançados em Filosofia Política', 'Universidade de Évora, Portugal', '2019'),
  ((SELECT id FROM professores WHERE slug = 'nlando-faustino'), 'Mestrado em Ciências da Educação (Administração e Gestão Educacional)', 'Universidade de Évora, Portugal', '2014'),
  ((SELECT id FROM professores WHERE slug = 'nlando-faustino'), 'Mestrado em Filosofia', 'Universidade Gregoriana (extensão RDC)', '2004'),
  ((SELECT id FROM professores WHERE slug = 'nlando-faustino'), 'Bacharelato em Filosofia', 'Seminário Maior de São Paulo, Uíge, Angola', NULL),

  ((SELECT id FROM professores WHERE slug = 'ana-rocha'), 'Doutoramento em Psicologia da Educação', 'Faculdade de Psicologia da Universidade de Lisboa, Portugal', NULL),
  ((SELECT id FROM professores WHERE slug = 'ana-rocha'), 'Especialização em Avaliação e Intervenção Psicológica em Contextos Educativos', 'Faculdade de Psicologia da Universidade de Lisboa, Portugal', NULL),

  ((SELECT id FROM professores WHERE slug = 'samuel-tumbula'), 'Doutoramento em Ciências da Educação (Administração e Organização Escolar)', 'Universidade Católica Portuguesa', '2020'),
  ((SELECT id FROM professores WHERE slug = 'samuel-tumbula'), 'Mestrado em Ciências da Educação (Administração e Organização Escolar)', 'Universidade Católica Portuguesa', '2010'),
  ((SELECT id FROM professores WHERE slug = 'samuel-tumbula'), 'MBA em Gerenciamento de Projectos', 'Fundação Getúlio Vargas, Brasil', '2017'),
  ((SELECT id FROM professores WHERE slug = 'samuel-tumbula'), 'Pós-Graduação em Direito do Trabalho e Segurança Social', 'Universidade Católica Portuguesa', '2021'),

  ((SELECT id FROM professores WHERE slug = 'albertino-candimba'), 'Doutoramento em Educação (Gestão Estratégica e Avaliação Institucional em IES)', NULL, NULL),
  ((SELECT id FROM professores WHERE slug = 'albertino-candimba'), 'Mestrado em Educação (Gestão Estratégica e Avaliação Institucional de IES)', NULL, NULL),
  ((SELECT id FROM professores WHERE slug = 'albertino-candimba'), 'Especialização em Ensino da Física e Química', 'Universidade de Aveiro', NULL),

  ((SELECT id FROM professores WHERE slug = 'pedro-fernandes'), 'MBA em Gestão de Empresas', 'Lisboa', NULL),
  ((SELECT id FROM professores WHERE slug = 'pedro-fernandes'), 'Licenciatura em Gestão de Empresas', 'Lisboa', NULL),

  ((SELECT id FROM professores WHERE slug = 'jose-chivinda'), 'Doutoramento em Ciências da Educação', 'Universidade Católica Portuguesa', NULL),

  ((SELECT id FROM professores WHERE slug = 'joao-francisco'), 'Doutoramento em Direito', 'Universitat de València, Espanha', '2021'),
  ((SELECT id FROM professores WHERE slug = 'joao-francisco'), 'Mestrado em Direito', 'Universitat de València, Espanha', '2016'),

  ((SELECT id FROM professores WHERE slug = 'maria-helena-miguel'), 'Mestrado em Ensino da Língua Portuguesa', 'ISCED, Luanda', '2009'),
  ((SELECT id FROM professores WHERE slug = 'maria-helena-miguel'), 'Licenciatura em Língua Portuguesa', 'ISCED, Luanda', '1997');

-- Insert Publicações (produção científica real do CIEI referenciada no documento institucional)
INSERT INTO publicacao (professor_id, titulo, revista, ano) VALUES
  ((SELECT id FROM professores WHERE slug = 'helena-veloso'),
   'Atitudes das famílias face aos membros portadores de Psicose: estudo de caso do hospital psiquiátrico do Lubango e do Centro de Reabilitação do Lubango, em Angola',
   'Revista Magazine', '2024'),
  ((SELECT id FROM professores WHERE slug = 'mangani-lopes'),
   'Atitudes das famílias face aos membros portadores de Psicose: estudo de caso do hospital psiquiátrico do Lubango e do Centro de Reabilitação do Lubango, em Angola',
   'Revista Magazine', '2024');
